// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vhetouswguygdowtvxxm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZoZXRvdXN3Z3V5Z2Rvd3R2eHhtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxOTIxODUsImV4cCI6MjA2NTc2ODE4NX0.kVfUKtYMSi2P__VS2g29OSvAyP87CJAA_IpCkSraH8E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);